// JLPT N5 단어 데이터
// 형식: { id, kanji, reading, type, meaning, example, exTrans }
// type: 'noun' | 'verb' | 'adj' | 'adv'

const VOCAB_N5 = [
  // ── あ ──
  {id:1,   kanji:'会う',      reading:'あう',       type:'verb', meaning:'만나다',           example:'友達に会います。',       exTrans:'친구를 만납니다.'},
  {id:2,   kanji:'青い',      reading:'あおい',      type:'adj',  meaning:'파랗다',           example:'空が青いです。',         exTrans:'하늘이 파랗습니다.'},
  {id:3,   kanji:'赤い',      reading:'あかい',      type:'adj',  meaning:'빨갛다',           example:'赤いバラです。',         exTrans:'빨간 장미입니다.'},
  {id:4,   kanji:'明るい',    reading:'あかるい',    type:'adj',  meaning:'밝다',             example:'部屋が明るいです。',     exTrans:'방이 밝습니다.'},
  {id:5,   kanji:'秋',        reading:'あき',        type:'noun', meaning:'가을',             example:'秋は涼しいです。',       exTrans:'가을은 시원합니다.'},
  {id:6,   kanji:'開ける',    reading:'あける',      type:'verb', meaning:'열다',             example:'窓を開けてください。',   exTrans:'창문을 열어 주세요.'},
  {id:7,   kanji:'朝',        reading:'あさ',        type:'noun', meaning:'아침',             example:'朝ご飯を食べます。',     exTrans:'아침밥을 먹습니다.'},
  {id:8,   kanji:'足',        reading:'あし',        type:'noun', meaning:'발, 다리',         example:'足が痛いです。',         exTrans:'발이 아픕니다.'},
  {id:9,   kanji:'明日',      reading:'あした',      type:'noun', meaning:'내일',             example:'明日また来ます。',       exTrans:'내일 또 오겠습니다.'},
  {id:10,  kanji:'遊ぶ',      reading:'あそぶ',      type:'verb', meaning:'놀다',             example:'公園で遊びます。',       exTrans:'공원에서 놉니다.'},
  {id:11,  kanji:'暖かい',    reading:'あたたかい',  type:'adj',  meaning:'따뜻하다',         example:'今日は暖かいですね。',   exTrans:'오늘은 따뜻하네요.'},
  {id:12,  kanji:'頭',        reading:'あたま',      type:'noun', meaning:'머리',             example:'頭が痛いです。',         exTrans:'머리가 아픕니다.'},
  {id:13,  kanji:'新しい',    reading:'あたらしい',  type:'adj',  meaning:'새롭다',           example:'新しい本を買いました。', exTrans:'새 책을 샀습니다.'},
  {id:14,  kanji:'暑い',      reading:'あつい',      type:'adj',  meaning:'덥다',             example:'夏は暑いです。',         exTrans:'여름은 덥습니다.'},
  {id:15,  kanji:'厚い',      reading:'あつい',      type:'adj',  meaning:'두껍다',           example:'厚い本ですね。',         exTrans:'두꺼운 책이네요.'},
  {id:16,  kanji:'あなた',    reading:'あなた',      type:'noun', meaning:'당신',             example:'あなたの名前は？',       exTrans:'당신의 이름은?'},
  {id:17,  kanji:'兄',        reading:'あに',        type:'noun', meaning:'(나의) 형, 오빠',  example:'兄は会社員です。',       exTrans:'형은 회사원입니다.'},
  {id:18,  kanji:'姉',        reading:'あね',        type:'noun', meaning:'(나의) 누나, 언니', example:'姉は先生です。',         exTrans:'누나는 선생님입니다.'},
  {id:19,  kanji:'あまり',    reading:'あまり',      type:'adv',  meaning:'별로 (～ない)',    example:'あまり好きじゃない。',   exTrans:'별로 좋아하지 않는다.'},
  {id:20,  kanji:'雨',        reading:'あめ',        type:'noun', meaning:'비',               example:'雨が降っています。',     exTrans:'비가 내리고 있습니다.'},
  {id:21,  kanji:'洗う',      reading:'あらう',      type:'verb', meaning:'씻다',             example:'手を洗います。',         exTrans:'손을 씻습니다.'},
  {id:22,  kanji:'ある',      reading:'ある',        type:'verb', meaning:'있다 (사물)',      example:'机の上に本があります。', exTrans:'책상 위에 책이 있습니다.'},
  {id:23,  kanji:'歩く',      reading:'あるく',      type:'verb', meaning:'걷다',             example:'毎日歩いています。',     exTrans:'매일 걷고 있습니다.'},
  {id:24,  kanji:'いい',      reading:'いい',        type:'adj',  meaning:'좋다',             example:'いい天気ですね。',       exTrans:'좋은 날씨네요.'},
  {id:25,  kanji:'言う',      reading:'いう',        type:'verb', meaning:'말하다',           example:'名前を言います。',       exTrans:'이름을 말합니다.'},
  {id:26,  kanji:'家',        reading:'いえ',        type:'noun', meaning:'집',               example:'家に帰ります。',         exTrans:'집에 돌아갑니다.'},
  {id:27,  kanji:'行く',      reading:'いく',        type:'verb', meaning:'가다',             example:'学校に行きます。',       exTrans:'학교에 갑니다.'},
  {id:28,  kanji:'医者',      reading:'いしゃ',      type:'noun', meaning:'의사',             example:'医者に行きます。',       exTrans:'의사에게 갑니다.'},
  {id:29,  kanji:'忙しい',    reading:'いそがしい',  type:'adj',  meaning:'바쁘다',           example:'今日は忙しいです。',     exTrans:'오늘은 바쁩니다.'},
  {id:30,  kanji:'いつ',      reading:'いつ',        type:'adv',  meaning:'언제',             example:'いつ来ますか。',         exTrans:'언제 옵니까?'},
  {id:31,  kanji:'一緒に',    reading:'いっしょに',  type:'adv',  meaning:'함께',             example:'一緒に行きましょう。',   exTrans:'함께 갑시다.'},
  {id:32,  kanji:'いつも',    reading:'いつも',      type:'adv',  meaning:'항상',             example:'いつも元気です。',       exTrans:'항상 건강합니다.'},
  {id:33,  kanji:'犬',        reading:'いぬ',        type:'noun', meaning:'개',               example:'犬が好きです。',         exTrans:'개를 좋아합니다.'},
  {id:34,  kanji:'今',        reading:'いま',        type:'noun', meaning:'지금',             example:'今何時ですか。',         exTrans:'지금 몇 시입니까?'},
  {id:35,  kanji:'妹',        reading:'いもうと',    type:'noun', meaning:'(나의) 여동생',    example:'妹は学生です。',         exTrans:'여동생은 학생입니다.'},
  {id:36,  kanji:'入れる',    reading:'いれる',      type:'verb', meaning:'넣다',             example:'鞄に入れます。',         exTrans:'가방에 넣습니다.'},
  {id:37,  kanji:'色',        reading:'いろ',        type:'noun', meaning:'색',               example:'何色が好きですか。',     exTrans:'무슨 색을 좋아합니까?'},
  {id:38,  kanji:'上',        reading:'うえ',        type:'noun', meaning:'위',               example:'机の上にあります。',     exTrans:'책상 위에 있습니다.'},
  {id:39,  kanji:'後ろ',      reading:'うしろ',      type:'noun', meaning:'뒤',               example:'後ろに座ります。',       exTrans:'뒤에 앉습니다.'},
  {id:40,  kanji:'薄い',      reading:'うすい',      type:'adj',  meaning:'얇다, 연하다',     example:'薄いノートです。',       exTrans:'얇은 노트입니다.'},
  {id:41,  kanji:'歌',        reading:'うた',        type:'noun', meaning:'노래',             example:'歌を歌います。',         exTrans:'노래를 부릅니다.'},
  {id:42,  kanji:'生まれる',  reading:'うまれる',    type:'verb', meaning:'태어나다',         example:'東京で生まれました。',   exTrans:'도쿄에서 태어났습니다.'},
  {id:43,  kanji:'海',        reading:'うみ',        type:'noun', meaning:'바다',             example:'海で泳ぎます。',         exTrans:'바다에서 수영합니다.'},
  {id:44,  kanji:'売る',      reading:'うる',        type:'verb', meaning:'팔다',             example:'本を売ります。',         exTrans:'책을 팝니다.'},
  {id:45,  kanji:'映画',      reading:'えいが',      type:'noun', meaning:'영화',             example:'映画を見ます。',         exTrans:'영화를 봅니다.'},
  {id:46,  kanji:'駅',        reading:'えき',        type:'noun', meaning:'역',               example:'駅まで歩きます。',       exTrans:'역까지 걷습니다.'},
  {id:47,  kanji:'鉛筆',      reading:'えんぴつ',    type:'noun', meaning:'연필',             example:'鉛筆で書きます。',       exTrans:'연필로 씁니다.'},
  {id:48,  kanji:'美味しい',  reading:'おいしい',    type:'adj',  meaning:'맛있다',           example:'このラーメンは美味しい。',exTrans:'이 라면은 맛있다.'},
  {id:49,  kanji:'多い',      reading:'おおい',      type:'adj',  meaning:'많다',             example:'人が多いです。',         exTrans:'사람이 많습니다.'},
  {id:50,  kanji:'大きい',    reading:'おおきい',    type:'adj',  meaning:'크다',             example:'大きい犬がいます。',     exTrans:'큰 개가 있습니다.'},
  {id:51,  kanji:'お母さん',  reading:'おかあさん',  type:'noun', meaning:'어머니',           example:'お母さんが好きです。',   exTrans:'어머니를 좋아합니다.'},
  {id:52,  kanji:'起きる',    reading:'おきる',      type:'verb', meaning:'일어나다',         example:'朝7時に起きます。',     exTrans:'아침 7시에 일어납니다.'},
  {id:53,  kanji:'置く',      reading:'おく',        type:'verb', meaning:'놓다',             example:'机の上に置きます。',     exTrans:'책상 위에 놓습니다.'},
  {id:54,  kanji:'お兄さん',  reading:'おにいさん',  type:'noun', meaning:'형, 오빠',         example:'お兄さんは背が高い。',   exTrans:'형은 키가 큽니다.'},
  {id:55,  kanji:'お姉さん',  reading:'おねえさん',  type:'noun', meaning:'누나, 언니',       example:'お姉さんは優しい。',     exTrans:'누나는 상냥합니다.'},
  {id:56,  kanji:'お父さん',  reading:'おとうさん',  type:'noun', meaning:'아버지',           example:'お父さんが帰りました。', exTrans:'아버지가 돌아왔습니다.'},
  {id:57,  kanji:'弟',        reading:'おとうと',    type:'noun', meaning:'(나의) 남동생',    example:'弟は小学生です。',       exTrans:'남동생은 초등학생입니다.'},
  {id:58,  kanji:'男',        reading:'おとこ',      type:'noun', meaning:'남자',             example:'男の人がいます。',       exTrans:'남자가 있습니다.'},
  {id:59,  kanji:'一昨日',    reading:'おととい',    type:'noun', meaning:'그저께',           example:'一昨日会いました。',     exTrans:'그저께 만났습니다.'},
  {id:60,  kanji:'面白い',    reading:'おもしろい',  type:'adj',  meaning:'재미있다',         example:'この映画は面白い。',     exTrans:'이 영화는 재미있습니다.'},
  {id:61,  kanji:'泳ぐ',      reading:'およぐ',      type:'verb', meaning:'수영하다',         example:'プールで泳ぎます。',     exTrans:'수영장에서 수영합니다.'},
  {id:62,  kanji:'終わる',    reading:'おわる',      type:'verb', meaning:'끝나다',           example:'授業が終わります。',     exTrans:'수업이 끝납니다.'},
  // ── か ──
  {id:63,  kanji:'外国',      reading:'がいこく',    type:'noun', meaning:'외국',             example:'外国に行きたい。',       exTrans:'외국에 가고 싶다.'},
  {id:64,  kanji:'買い物',    reading:'かいもの',    type:'noun', meaning:'쇼핑, 장보기',     example:'買い物に行きます。',     exTrans:'쇼핑하러 갑니다.'},
  {id:65,  kanji:'帰る',      reading:'かえる',      type:'verb', meaning:'돌아가다',         example:'家に帰ります。',         exTrans:'집에 돌아갑니다.'},
  {id:66,  kanji:'書く',      reading:'かく',        type:'verb', meaning:'쓰다',             example:'手紙を書きます。',       exTrans:'편지를 씁니다.'},
  {id:67,  kanji:'学生',      reading:'がくせい',    type:'noun', meaning:'학생',             example:'私は学生です。',         exTrans:'저는 학생입니다.'},
  {id:68,  kanji:'傘',        reading:'かさ',        type:'noun', meaning:'우산',             example:'傘を持ってきました。',   exTrans:'우산을 가져왔습니다.'},
  {id:69,  kanji:'風',        reading:'かぜ',        type:'noun', meaning:'바람',             example:'風が強いです。',         exTrans:'바람이 강합니다.'},
  {id:70,  kanji:'風邪',      reading:'かぜ',        type:'noun', meaning:'감기',             example:'風邪を引きました。',     exTrans:'감기에 걸렸습니다.'},
  {id:71,  kanji:'家族',      reading:'かぞく',      type:'noun', meaning:'가족',             example:'家族と住んでいます。',   exTrans:'가족과 살고 있습니다.'},
  {id:72,  kanji:'学校',      reading:'がっこう',    type:'noun', meaning:'학교',             example:'学校は9時から始まる。',  exTrans:'학교는 9시부터 시작합니다.'},
  {id:73,  kanji:'かばん',    reading:'かばん',      type:'noun', meaning:'가방',             example:'かばんを持ちます。',     exTrans:'가방을 들고 있습니다.'},
  {id:74,  kanji:'体',        reading:'からだ',      type:'noun', meaning:'몸',               example:'体が丈夫です。',         exTrans:'몸이 건강합니다.'},
  {id:75,  kanji:'借りる',    reading:'かりる',      type:'verb', meaning:'빌리다',           example:'本を借ります。',         exTrans:'책을 빌립니다.'},
  {id:76,  kanji:'軽い',      reading:'かるい',      type:'adj',  meaning:'가볍다',           example:'このかばんは軽い。',     exTrans:'이 가방은 가볍습니다.'},
  {id:77,  kanji:'川',        reading:'かわ',        type:'noun', meaning:'강',               example:'川で魚を釣ります。',     exTrans:'강에서 물고기를 낚습니다.'},
  {id:78,  kanji:'漢字',      reading:'かんじ',      type:'noun', meaning:'한자',             example:'漢字を勉強します。',     exTrans:'한자를 공부합니다.'},
  {id:79,  kanji:'木',        reading:'き',          type:'noun', meaning:'나무',             example:'大きい木がある。',       exTrans:'큰 나무가 있습니다.'},
  {id:80,  kanji:'黄色い',    reading:'きいろい',    type:'adj',  meaning:'노랗다',           example:'黄色い花が咲いた。',     exTrans:'노란 꽃이 피었습니다.'},
  {id:81,  kanji:'聞く',      reading:'きく',        type:'verb', meaning:'듣다, 묻다',       example:'音楽を聞きます。',       exTrans:'음악을 듣습니다.'},
  {id:82,  kanji:'汚い',      reading:'きたない',    type:'adj',  meaning:'더럽다',           example:'部屋が汚いです。',       exTrans:'방이 더럽습니다.'},
  {id:83,  kanji:'切る',      reading:'きる',        type:'verb', meaning:'자르다',           example:'パンを切ります。',       exTrans:'빵을 자릅니다.'},
  {id:84,  kanji:'着る',      reading:'きる',        type:'verb', meaning:'입다',             example:'シャツを着ます。',       exTrans:'셔츠를 입습니다.'},
  {id:85,  kanji:'銀行',      reading:'ぎんこう',    type:'noun', meaning:'은행',             example:'銀行でお金を引き出す。', exTrans:'은행에서 돈을 뽑습니다.'},
  {id:86,  kanji:'空港',      reading:'くうこう',    type:'noun', meaning:'공항',             example:'空港まで送ります。',     exTrans:'공항까지 데려다 줍니다.'},
  {id:87,  kanji:'薬',        reading:'くすり',      type:'noun', meaning:'약',               example:'薬を飲みます。',         exTrans:'약을 먹습니다.'},
  {id:88,  kanji:'果物',      reading:'くだもの',    type:'noun', meaning:'과일',             example:'果物が好きです。',       exTrans:'과일을 좋아합니다.'},
  {id:89,  kanji:'口',        reading:'くち',        type:'noun', meaning:'입',               example:'口を開けてください。',   exTrans:'입을 벌려 주세요.'},
  {id:90,  kanji:'靴',        reading:'くつ',        type:'noun', meaning:'신발',             example:'新しい靴を買いました。', exTrans:'새 신발을 샀습니다.'},
  {id:91,  kanji:'国',        reading:'くに',        type:'noun', meaning:'나라',             example:'どこの国ですか。',       exTrans:'어느 나라입니까?'},
  {id:92,  kanji:'曇り',      reading:'くもり',      type:'noun', meaning:'흐림',             example:'今日は曇りです。',       exTrans:'오늘은 흐립니다.'},
  {id:93,  kanji:'来る',      reading:'くる',        type:'verb', meaning:'오다',             example:'友達が来ます。',         exTrans:'친구가 옵니다.'},
  {id:94,  kanji:'黒い',      reading:'くろい',      type:'adj',  meaning:'검다',             example:'黒いかばんです。',       exTrans:'검은 가방입니다.'},
  {id:95,  kanji:'今朝',      reading:'けさ',        type:'noun', meaning:'오늘 아침',         example:'今朝早く起きました。',   exTrans:'오늘 아침 일찍 일어났습니다.'},
  {id:96,  kanji:'結婚',      reading:'けっこん',    type:'noun', meaning:'결혼',             example:'来年結婚します。',       exTrans:'내년에 결혼합니다.'},
  {id:97,  kanji:'元気',      reading:'げんき',      type:'adj',  meaning:'건강하다, 활기차다',example:'元気ですか。',           exTrans:'잘 지내십니까?'},
  {id:98,  kanji:'公園',      reading:'こうえん',    type:'noun', meaning:'공원',             example:'公園を散歩します。',     exTrans:'공원을 산책합니다.'},
  {id:99,  kanji:'高校',      reading:'こうこう',    type:'noun', meaning:'고등학교',         example:'高校に通っています。',   exTrans:'고등학교에 다니고 있습니다.'},
  {id:100, kanji:'交差点',    reading:'こうさてん',  type:'noun', meaning:'교차로',           example:'交差点を右に曲がります。',exTrans:'교차로에서 오른쪽으로 돕니다.'},
  {id:101, kanji:'声',        reading:'こえ',        type:'noun', meaning:'목소리',           example:'大きい声で話します。',   exTrans:'큰 소리로 말합니다.'},
  {id:102, kanji:'ここ',      reading:'ここ',        type:'noun', meaning:'여기',             example:'ここに座ります。',       exTrans:'여기에 앉습니다.'},
  {id:103, kanji:'午後',      reading:'ごご',        type:'noun', meaning:'오후',             example:'午後3時に会います。',    exTrans:'오후 3시에 만납니다.'},
  {id:104, kanji:'午前',      reading:'ごぜん',      type:'noun', meaning:'오전',             example:'午前中に終わります。',   exTrans:'오전 중에 끝납니다.'},
  {id:105, kanji:'子供',      reading:'こども',      type:'noun', meaning:'어린이',           example:'子供が遊んでいます。',   exTrans:'어린이가 놀고 있습니다.'},
  {id:106, kanji:'これ',      reading:'これ',        type:'noun', meaning:'이것',             example:'これは何ですか。',       exTrans:'이것은 무엇입니까?'},
  {id:107, kanji:'今週',      reading:'こんしゅう',  type:'noun', meaning:'이번 주',           example:'今週忙しいです。',       exTrans:'이번 주는 바쁩니다.'},
  {id:108, kanji:'今月',      reading:'こんげつ',    type:'noun', meaning:'이번 달',           example:'今月から始まります。',   exTrans:'이번 달부터 시작합니다.'},
  {id:109, kanji:'今年',      reading:'ことし',      type:'noun', meaning:'올해',             example:'今年で30歳になります。', exTrans:'올해로 30살이 됩니다.'},
  // ── さ ──
  {id:110, kanji:'魚',        reading:'さかな',      type:'noun', meaning:'물고기, 생선',     example:'魚が好きです。',         exTrans:'생선을 좋아합니다.'},
  {id:111, kanji:'先',        reading:'さき',        type:'noun', meaning:'먼저, 앞',         example:'先に行きます。',         exTrans:'먼저 가겠습니다.'},
  {id:112, kanji:'寒い',      reading:'さむい',      type:'adj',  meaning:'춥다',             example:'冬は寒いです。',         exTrans:'겨울은 춥습니다.'},
  {id:113, kanji:'散歩',      reading:'さんぽ',      type:'noun', meaning:'산책',             example:'犬と散歩します。',       exTrans:'개와 산책합니다.'},
  {id:114, kanji:'塩',        reading:'しお',        type:'noun', meaning:'소금',             example:'塩を入れてください。',   exTrans:'소금을 넣어 주세요.'},
  {id:115, kanji:'時間',      reading:'じかん',      type:'noun', meaning:'시간',             example:'時間がありません。',     exTrans:'시간이 없습니다.'},
  {id:116, kanji:'仕事',      reading:'しごと',      type:'noun', meaning:'일, 직업',         example:'仕事が好きです。',       exTrans:'일을 좋아합니다.'},
  {id:117, kanji:'辞書',      reading:'じしょ',      type:'noun', meaning:'사전',             example:'辞書で調べます。',       exTrans:'사전으로 찾습니다.'},
  {id:118, kanji:'下',        reading:'した',        type:'noun', meaning:'아래',             example:'机の下にあります。',     exTrans:'책상 아래에 있습니다.'},
  {id:119, kanji:'七',        reading:'しち',        type:'noun', meaning:'7, 일곱',          example:'七時に起きます。',       exTrans:'7시에 일어납니다.'},
  {id:120, kanji:'自転車',    reading:'じてんしゃ',  type:'noun', meaning:'자전거',           example:'自転車で行きます。',     exTrans:'자전거로 갑니다.'},
  {id:121, kanji:'じゃあ',    reading:'じゃあ',      type:'adv',  meaning:'그럼',             example:'じゃあ、また明日。',     exTrans:'그럼, 또 내일.'},
  {id:122, kanji:'写真',      reading:'しゃしん',    type:'noun', meaning:'사진',             example:'写真を撮ります。',       exTrans:'사진을 찍습니다.'},
  {id:123, kanji:'新聞',      reading:'しんぶん',    type:'noun', meaning:'신문',             example:'毎日新聞を読みます。',   exTrans:'매일 신문을 읽습니다.'},
  {id:124, kanji:'好き',      reading:'すき',        type:'adj',  meaning:'좋아하다',         example:'音楽が好きです。',       exTrans:'음악을 좋아합니다.'},
  {id:125, kanji:'少し',      reading:'すこし',      type:'adv',  meaning:'조금',             example:'少し待ってください。',   exTrans:'조금 기다려 주세요.'},
  {id:126, kanji:'すぐ',      reading:'すぐ',        type:'adv',  meaning:'곧, 바로',         example:'すぐ来ます。',           exTrans:'곧 옵니다.'},
  {id:127, kanji:'涼しい',    reading:'すずしい',    type:'adj',  meaning:'시원하다',         example:'秋は涼しいです。',       exTrans:'가을은 시원합니다.'},
  {id:128, kanji:'住む',      reading:'すむ',        type:'verb', meaning:'살다, 거주하다',   example:'東京に住んでいます。',   exTrans:'도쿄에 살고 있습니다.'},
  {id:129, kanji:'背',        reading:'せ',          type:'noun', meaning:'키, 등',           example:'背が高いです。',         exTrans:'키가 큽니다.'},
  {id:130, kanji:'生徒',      reading:'せいと',      type:'noun', meaning:'학생, 생도',       example:'生徒が多いです。',       exTrans:'학생이 많습니다.'},
  {id:131, kanji:'背広',      reading:'せびろ',      type:'noun', meaning:'양복',             example:'背広を着て行きます。',   exTrans:'양복을 입고 갑니다.'},
  {id:132, kanji:'先生',      reading:'せんせい',    type:'noun', meaning:'선생님',           example:'先生に聞きます。',       exTrans:'선생님께 묻습니다.'},
  {id:133, kanji:'掃除',      reading:'そうじ',      type:'noun', meaning:'청소',             example:'部屋を掃除します。',     exTrans:'방을 청소합니다.'},
  {id:134, kanji:'空',        reading:'そら',        type:'noun', meaning:'하늘',             example:'空が青いです。',         exTrans:'하늘이 파랗습니다.'},
  {id:135, kanji:'それ',      reading:'それ',        type:'noun', meaning:'그것',             example:'それは何ですか。',       exTrans:'그것은 무엇입니까?'},
  // ── た ──
  {id:136, kanji:'大学',      reading:'だいがく',    type:'noun', meaning:'대학교',           example:'大学で勉強します。',     exTrans:'대학에서 공부합니다.'},
  {id:137, kanji:'大使館',    reading:'たいしかん',  type:'noun', meaning:'대사관',           example:'大使館に行きます。',     exTrans:'대사관에 갑니다.'},
  {id:138, kanji:'食べ物',    reading:'たべもの',    type:'noun', meaning:'음식',             example:'食べ物が好きです。',     exTrans:'음식을 좋아합니다.'},
  {id:139, kanji:'食べる',    reading:'たべる',      type:'verb', meaning:'먹다',             example:'ご飯を食べます。',       exTrans:'밥을 먹습니다.'},
  {id:140, kanji:'誰',        reading:'だれ',        type:'noun', meaning:'누구',             example:'誰が来ましたか。',       exTrans:'누가 왔습니까?'},
  {id:141, kanji:'小さい',    reading:'ちいさい',    type:'adj',  meaning:'작다',             example:'小さい犬です。',         exTrans:'작은 개입니다.'},
  {id:142, kanji:'近い',      reading:'ちかい',      type:'adj',  meaning:'가깝다',           example:'駅が近いです。',         exTrans:'역이 가깝습니다.'},
  {id:143, kanji:'地下鉄',    reading:'ちかてつ',    type:'noun', meaning:'지하철',           example:'地下鉄で行きます。',     exTrans:'지하철로 갑니다.'},
  {id:144, kanji:'ちょっと',  reading:'ちょっと',    type:'adv',  meaning:'잠깐, 조금',       example:'ちょっと待ってください。',exTrans:'잠깐 기다려 주세요.'},
  {id:145, kanji:'月',        reading:'つき',        type:'noun', meaning:'달',               example:'月がきれいです。',       exTrans:'달이 예쁩니다.'},
  {id:146, kanji:'つける',    reading:'つける',      type:'verb', meaning:'켜다',             example:'電気をつけます。',       exTrans:'전등을 켭니다.'},
  {id:147, kanji:'強い',      reading:'つよい',      type:'adj',  meaning:'강하다',           example:'強い風が吹きました。',   exTrans:'강한 바람이 불었습니다.'},
  {id:148, kanji:'手',        reading:'て',          type:'noun', meaning:'손',               example:'手を洗います。',         exTrans:'손을 씻습니다.'},
  {id:149, kanji:'テーブル',  reading:'テーブル',    type:'noun', meaning:'테이블',           example:'テーブルに置きます。',   exTrans:'테이블에 놓습니다.'},
  {id:150, kanji:'電気',      reading:'でんき',      type:'noun', meaning:'전기, 전등',       example:'電気を消します。',       exTrans:'전등을 끕니다.'},
  {id:151, kanji:'電車',      reading:'でんしゃ',    type:'noun', meaning:'전철',             example:'電車で通勤します。',     exTrans:'전철로 통근합니다.'},
  {id:152, kanji:'電話',      reading:'でんわ',      type:'noun', meaning:'전화',             example:'電話をかけます。',       exTrans:'전화를 겁니다.'},
  {id:153, kanji:'戸',        reading:'と',          type:'noun', meaning:'문',               example:'戸を閉めてください。',   exTrans:'문을 닫아 주세요.'},
  {id:154, kanji:'どう',      reading:'どう',        type:'adv',  meaning:'어떻게',           example:'どうしましたか。',       exTrans:'어떻게 됐습니까?'},
  {id:155, kanji:'遠い',      reading:'とおい',      type:'adj',  meaning:'멀다',             example:'学校が遠いです。',       exTrans:'학교가 멉니다.'},
  {id:156, kanji:'時計',      reading:'とけい',      type:'noun', meaning:'시계',             example:'時計を見ます。',         exTrans:'시계를 봅니다.'},
  {id:157, kanji:'どこ',      reading:'どこ',        type:'noun', meaning:'어디',             example:'どこに行きますか。',     exTrans:'어디에 갑니까?'},
  {id:158, kanji:'図書館',    reading:'としょかん',  type:'noun', meaning:'도서관',           example:'図書館で本を読みます。', exTrans:'도서관에서 책을 읽습니다.'},
  {id:159, kanji:'どの',      reading:'どの',        type:'adj',  meaning:'어느',             example:'どの本が好きですか。',   exTrans:'어느 책을 좋아합니까?'},
  {id:160, kanji:'飛ぶ',      reading:'とぶ',        type:'verb', meaning:'날다',             example:'鳥が飛んでいます。',     exTrans:'새가 날고 있습니다.'},
  {id:161, kanji:'友達',      reading:'ともだち',    type:'noun', meaning:'친구',             example:'友達と遊びます。',       exTrans:'친구와 놉니다.'},
  {id:162, kanji:'鳥',        reading:'とり',        type:'noun', meaning:'새',               example:'鳥が鳴いています。',     exTrans:'새가 울고 있습니다.'},
  {id:163, kanji:'撮る',      reading:'とる',        type:'verb', meaning:'찍다',             example:'写真を撮ります。',       exTrans:'사진을 찍습니다.'},
  // ── な ──
  {id:164, kanji:'中',        reading:'なか',        type:'noun', meaning:'안, 속',           example:'箱の中にあります。',     exTrans:'상자 안에 있습니다.'},
  {id:165, kanji:'長い',      reading:'ながい',      type:'adj',  meaning:'길다',             example:'長い道です。',           exTrans:'긴 길입니다.'},
  {id:166, kanji:'夏',        reading:'なつ',        type:'noun', meaning:'여름',             example:'夏が好きです。',         exTrans:'여름을 좋아합니다.'},
  {id:167, kanji:'何',        reading:'なに',        type:'noun', meaning:'무엇',             example:'何を食べますか。',       exTrans:'무엇을 먹겠습니까?'},
  {id:168, kanji:'習う',      reading:'ならう',      type:'verb', meaning:'배우다',           example:'ピアノを習います。',     exTrans:'피아노를 배웁니다.'},
  {id:169, kanji:'肉',        reading:'にく',        type:'noun', meaning:'고기',             example:'肉が好きです。',         exTrans:'고기를 좋아합니다.'},
  {id:170, kanji:'西',        reading:'にし',        type:'noun', meaning:'서쪽',             example:'西に向かいます。',       exTrans:'서쪽으로 향합니다.'},
  {id:171, kanji:'日曜日',    reading:'にちようび',  type:'noun', meaning:'일요일',           example:'日曜日は休みです。',     exTrans:'일요일은 쉽니다.'},
  {id:172, kanji:'庭',        reading:'にわ',        type:'noun', meaning:'정원',             example:'庭に花があります。',     exTrans:'정원에 꽃이 있습니다.'},
  {id:173, kanji:'脱ぐ',      reading:'ぬぐ',        type:'verb', meaning:'벗다',             example:'靴を脱ぎます。',         exTrans:'신발을 벗습니다.'},
  {id:174, kanji:'飲む',      reading:'のむ',        type:'verb', meaning:'마시다',           example:'水を飲みます。',         exTrans:'물을 마십니다.'},
  {id:175, kanji:'乗る',      reading:'のる',        type:'verb', meaning:'타다',             example:'電車に乗ります。',       exTrans:'전철을 탑니다.'},
  // ── は ──
  {id:176, kanji:'入る',      reading:'はいる',      type:'verb', meaning:'들어가다',         example:'部屋に入ります。',       exTrans:'방에 들어갑니다.'},
  {id:177, kanji:'履く',      reading:'はく',        type:'verb', meaning:'(하의를) 입다, 신다',example:'ズボンを履きます。',   exTrans:'바지를 입습니다.'},
  {id:178, kanji:'始まる',    reading:'はじまる',    type:'verb', meaning:'시작되다',         example:'授業が始まります。',     exTrans:'수업이 시작됩니다.'},
  {id:179, kanji:'走る',      reading:'はしる',      type:'verb', meaning:'달리다',           example:'公園を走ります。',       exTrans:'공원을 달립니다.'},
  {id:180, kanji:'花',        reading:'はな',        type:'noun', meaning:'꽃',               example:'花がきれいです。',       exTrans:'꽃이 예쁩니다.'},
  {id:181, kanji:'話す',      reading:'はなす',      type:'verb', meaning:'말하다',           example:'日本語で話します。',     exTrans:'일본어로 말합니다.'},
  {id:182, kanji:'春',        reading:'はる',        type:'noun', meaning:'봄',               example:'春が来ました。',         exTrans:'봄이 왔습니다.'},
  {id:183, kanji:'晴れ',      reading:'はれ',        type:'noun', meaning:'맑음',             example:'今日は晴れです。',       exTrans:'오늘은 맑습니다.'},
  {id:184, kanji:'半分',      reading:'はんぶん',    type:'noun', meaning:'절반',             example:'半分食べました。',       exTrans:'절반 먹었습니다.'},
  {id:185, kanji:'東',        reading:'ひがし',      type:'noun', meaning:'동쪽',             example:'東から太陽が昇ります。', exTrans:'동쪽에서 해가 뜹니다.'},
  {id:186, kanji:'低い',      reading:'ひくい',      type:'adj',  meaning:'낮다',             example:'低い声で話します。',     exTrans:'낮은 소리로 말합니다.'},
  {id:187, kanji:'左',        reading:'ひだり',      type:'noun', meaning:'왼쪽',             example:'左に曲がります。',       exTrans:'왼쪽으로 돕니다.'},
  {id:188, kanji:'人',        reading:'ひと',        type:'noun', meaning:'사람',             example:'あの人は誰ですか。',     exTrans:'저 사람은 누구입니까?'},
  {id:189, kanji:'暇',        reading:'ひま',        type:'noun', meaning:'한가함',           example:'今日は暇です。',         exTrans:'오늘은 한가합니다.'},
  {id:190, kanji:'病院',      reading:'びょういん',  type:'noun', meaning:'병원',             example:'病院に行きます。',       exTrans:'병원에 갑니다.'},
  {id:191, kanji:'太い',      reading:'ふとい',      type:'adj',  meaning:'굵다, 뚱뚱하다',   example:'太い木です。',           exTrans:'굵은 나무입니다.'},
  {id:192, kanji:'冬',        reading:'ふゆ',        type:'noun', meaning:'겨울',             example:'冬は寒いです。',         exTrans:'겨울은 춥습니다.'},
  {id:193, kanji:'降る',      reading:'ふる',        type:'verb', meaning:'(비, 눈이) 내리다', example:'雨が降っています。',     exTrans:'비가 내리고 있습니다.'},
  {id:194, kanji:'古い',      reading:'ふるい',      type:'adj',  meaning:'오래되다',         example:'古い建物です。',         exTrans:'오래된 건물입니다.'},
  {id:195, kanji:'下手',      reading:'へた',        type:'adj',  meaning:'서투르다',         example:'料理が下手です。',       exTrans:'요리가 서툽니다.'},
  {id:196, kanji:'部屋',      reading:'へや',        type:'noun', meaning:'방',               example:'部屋が広いです。',       exTrans:'방이 넓습니다.'},
  {id:197, kanji:'勉強',      reading:'べんきょう',  type:'noun', meaning:'공부',             example:'毎日勉強します。',       exTrans:'매일 공부합니다.'},
  {id:198, kanji:'帽子',      reading:'ぼうし',      type:'noun', meaning:'모자',             example:'帽子をかぶります。',     exTrans:'모자를 씁니다.'},
  {id:199, kanji:'本',        reading:'ほん',        type:'noun', meaning:'책',               example:'本を読みます。',         exTrans:'책을 읽습니다.'},
  {id:200, kanji:'本棚',      reading:'ほんだな',    type:'noun', meaning:'책장',             example:'本棚に並んでいます。',   exTrans:'책장에 늘어서 있습니다.'},
  // ── ま ──
  {id:201, kanji:'毎朝',      reading:'まいあさ',    type:'noun', meaning:'매일 아침',         example:'毎朝7時に起きます。',    exTrans:'매일 아침 7시에 일어납니다.'},
  {id:202, kanji:'毎日',      reading:'まいにち',    type:'noun', meaning:'매일',             example:'毎日勉強します。',       exTrans:'매일 공부합니다.'},
  {id:203, kanji:'まだ',      reading:'まだ',        type:'adv',  meaning:'아직',             example:'まだ終わっていません。', exTrans:'아직 끝나지 않았습니다.'},
  {id:204, kanji:'まっすぐ',  reading:'まっすぐ',    type:'adv',  meaning:'똑바로',           example:'まっすぐ行ってください。',exTrans:'똑바로 가세요.'},
  {id:205, kanji:'窓',        reading:'まど',        type:'noun', meaning:'창문',             example:'窓を開けます。',         exTrans:'창문을 엽니다.'},
  {id:206, kanji:'右',        reading:'みぎ',        type:'noun', meaning:'오른쪽',           example:'右に曲がります。',       exTrans:'오른쪽으로 돕니다.'},
  {id:207, kanji:'短い',      reading:'みじかい',    type:'adj',  meaning:'짧다',             example:'短い時間でした。',       exTrans:'짧은 시간이었습니다.'},
  {id:208, kanji:'水',        reading:'みず',        type:'noun', meaning:'물',               example:'水を飲みます。',         exTrans:'물을 마십니다.'},
  {id:209, kanji:'店',        reading:'みせ',        type:'noun', meaning:'가게',             example:'新しい店ができました。', exTrans:'새 가게가 생겼습니다.'},
  {id:210, kanji:'道',        reading:'みち',        type:'noun', meaning:'길',               example:'この道を行きます。',     exTrans:'이 길을 갑니다.'},
  {id:211, kanji:'見る',      reading:'みる',        type:'verb', meaning:'보다',             example:'テレビを見ます。',       exTrans:'TV를 봅니다.'},
  {id:212, kanji:'難しい',    reading:'むずかしい',  type:'adj',  meaning:'어렵다',           example:'問題が難しいです。',     exTrans:'문제가 어렵습니다.'},
  {id:213, kanji:'目',        reading:'め',          type:'noun', meaning:'눈',               example:'目が大きいです。',       exTrans:'눈이 큽니다.'},
  {id:214, kanji:'持つ',      reading:'もつ',        type:'verb', meaning:'가지다, 들다',     example:'かばんを持ちます。',     exTrans:'가방을 듭니다.'},
  {id:215, kanji:'もっと',    reading:'もっと',      type:'adv',  meaning:'더, 더욱',         example:'もっとゆっくり話してください。',exTrans:'더 천천히 말해 주세요.'},
  // ── や ──
  {id:216, kanji:'野菜',      reading:'やさい',      type:'noun', meaning:'채소',             example:'野菜を食べます。',       exTrans:'채소를 먹습니다.'},
  {id:217, kanji:'安い',      reading:'やすい',      type:'adj',  meaning:'싸다',             example:'安い店です。',           exTrans:'싼 가게입니다.'},
  {id:218, kanji:'休む',      reading:'やすむ',      type:'verb', meaning:'쉬다',             example:'今日は休みます。',       exTrans:'오늘은 쉽니다.'},
  {id:219, kanji:'山',        reading:'やま',        type:'noun', meaning:'산',               example:'山に登ります。',         exTrans:'산에 오릅니다.'},
  {id:220, kanji:'夕方',      reading:'ゆうがた',    type:'noun', meaning:'저녁때',           example:'夕方5時に帰ります。',    exTrans:'저녁 5시에 돌아갑니다.'},
  {id:221, kanji:'有名',      reading:'ゆうめい',    type:'adj',  meaning:'유명하다',         example:'有名な店です。',         exTrans:'유명한 가게입니다.'},
  {id:222, kanji:'雪',        reading:'ゆき',        type:'noun', meaning:'눈',               example:'雪が降っています。',     exTrans:'눈이 내리고 있습니다.'},
  {id:223, kanji:'良い',      reading:'よい',        type:'adj',  meaning:'좋다',             example:'良い天気です。',         exTrans:'좋은 날씨입니다.'},
  {id:224, kanji:'曜日',      reading:'ようび',      type:'noun', meaning:'요일',             example:'何曜日ですか。',         exTrans:'무슨 요일입니까?'},
  {id:225, kanji:'読む',      reading:'よむ',        type:'verb', meaning:'읽다',             example:'本を読みます。',         exTrans:'책을 읽습니다.'},
  {id:226, kanji:'夜',        reading:'よる',        type:'noun', meaning:'밤',               example:'夜遅く寝ます。',         exTrans:'밤 늦게 잡니다.'},
  // ── ら ──
  {id:227, kanji:'来週',      reading:'らいしゅう',  type:'noun', meaning:'다음 주',           example:'来週また来ます。',       exTrans:'다음 주에 또 오겠습니다.'},
  {id:228, kanji:'来月',      reading:'らいげつ',    type:'noun', meaning:'다음 달',           example:'来月旅行します。',       exTrans:'다음 달에 여행합니다.'},
  {id:229, kanji:'来年',      reading:'らいねん',    type:'noun', meaning:'내년',             example:'来年卒業します。',       exTrans:'내년에 졸업합니다.'},
  {id:230, kanji:'旅行',      reading:'りょこう',    type:'noun', meaning:'여행',             example:'旅行が好きです。',       exTrans:'여행을 좋아합니다.'},
  {id:231, kanji:'料理',      reading:'りょうり',    type:'noun', meaning:'요리',             example:'料理を作ります。',       exTrans:'요리를 만듭니다.'},
  {id:232, kanji:'冷蔵庫',    reading:'れいぞうこ',  type:'noun', meaning:'냉장고',           example:'冷蔵庫に入れます。',     exTrans:'냉장고에 넣습니다.'},
  // ── わ ──
  {id:233, kanji:'分かる',    reading:'わかる',      type:'verb', meaning:'알다, 이해하다',   example:'日本語が分かります。',   exTrans:'일본어를 압니다.'},
  {id:234, kanji:'忘れる',    reading:'わすれる',    type:'verb', meaning:'잊다',             example:'名前を忘れました。',     exTrans:'이름을 잊었습니다.'},
  {id:235, kanji:'悪い',      reading:'わるい',      type:'adj',  meaning:'나쁘다',           example:'天気が悪いです。',       exTrans:'날씨가 나쁩니다.'},
];
