// JLPT N3 단어 데이터
// 형식: { id, kanji, reading, type, meaning, example, exTrans }
// type: 'noun' | 'verb' | 'adj' | 'adv'

const VOCAB_N3 = [
  // ── NOUNS ──
  {id:1,  kanji:'経験',    reading:'けいけん',     type:'noun', meaning:'경험',               example:'仕事の経験がありますか。',              exTrans:'업무 경험이 있으십니까?'},
  {id:2,  kanji:'理由',    reading:'りゆう',       type:'noun', meaning:'이유, 까닭',          example:'遅刻した理由を教えてください。',         exTrans:'지각한 이유를 알려 주세요.'},
  {id:3,  kanji:'習慣',    reading:'しゅうかん',   type:'noun', meaning:'습관, 관습',          example:'毎朝運動する習慣があります。',           exTrans:'매일 아침 운동하는 습관이 있습니다.'},
  {id:4,  kanji:'予定',    reading:'よてい',       type:'noun', meaning:'예정, 계획',          example:'週末の予定はありますか。',              exTrans:'주말 계획이 있습니까?'},
  {id:5,  kanji:'注意',    reading:'ちゅうい',     type:'noun', meaning:'주의, 주목',          example:'足元に注意してください。',              exTrans:'발밑에 주의하세요.'},
  {id:6,  kanji:'影響',    reading:'えいきょう',   type:'noun', meaning:'영향, 효과',          example:'天気は気分に影響します。',              exTrans:'날씨는 기분에 영향을 미칩니다.'},
  {id:7,  kanji:'改善',    reading:'かいぜん',     type:'noun', meaning:'개선',               example:'環境の改善が必要だ。',                  exTrans:'환경 개선이 필요하다.'},
  {id:8,  kanji:'可能性',  reading:'かのうせい',   type:'noun', meaning:'가능성',              example:'成功の可能性は高い。',                  exTrans:'성공할 가능성이 높다.'},
  {id:9,  kanji:'目的',    reading:'もくてき',     type:'noun', meaning:'목적, 목표',          example:'旅行の目的は何ですか。',                exTrans:'여행의 목적은 무엇입니까?'},
  {id:10, kanji:'原因',    reading:'げんいん',     type:'noun', meaning:'원인',               example:'事故の原因を調べています。',             exTrans:'사고의 원인을 조사하고 있습니다.'},
  {id:11, kanji:'結果',    reading:'けっか',       type:'noun', meaning:'결과',               example:'テストの結果が出ました。',              exTrans:'시험 결과가 나왔습니다.'},
  {id:12, kanji:'状況',    reading:'じょうきょう', type:'noun', meaning:'상황, 사정',          example:'現在の状況を説明してください。',         exTrans:'현재 상황을 설명해 주세요.'},
  {id:13, kanji:'意見',    reading:'いけん',       type:'noun', meaning:'의견',               example:'あなたの意見を聞かせてください。',       exTrans:'당신의 의견을 들려주세요.'},
  {id:14, kanji:'関係',    reading:'かんけい',     type:'noun', meaning:'관계',               example:'それは私には関係ない。',                exTrans:'그것은 나와 관계없다.'},
  {id:15, kanji:'問題',    reading:'もんだい',     type:'noun', meaning:'문제',               example:'環境問題は深刻だ。',                    exTrans:'환경 문제는 심각하다.'},
  {id:16, kanji:'解決',    reading:'かいけつ',     type:'noun', meaning:'해결',               example:'問題の解決策を探しています。',           exTrans:'문제의 해결책을 찾고 있습니다.'},
  {id:17, kanji:'社会',    reading:'しゃかい',     type:'noun', meaning:'사회',               example:'社会に貢献したい。',                    exTrans:'사회에 공헌하고 싶다.'},
  {id:18, kanji:'文化',    reading:'ぶんか',       type:'noun', meaning:'문화',               example:'日本の文化に興味があります。',           exTrans:'일본 문화에 관심이 있습니다.'},
  {id:19, kanji:'環境',    reading:'かんきょう',   type:'noun', meaning:'환경',               example:'環境を守ることが大切だ。',              exTrans:'환경을 지키는 것이 중요하다.'},
  {id:20, kanji:'地域',    reading:'ちいき',       type:'noun', meaning:'지역, 지방',          example:'この地域の人口は減っています。',         exTrans:'이 지역의 인구는 줄고 있습니다.'},
  {id:21, kanji:'政府',    reading:'せいふ',       type:'noun', meaning:'정부',               example:'政府は新しい法律を作った。',            exTrans:'정부는 새 법률을 만들었다.'},
  {id:22, kanji:'制度',    reading:'せいど',       type:'noun', meaning:'제도',               example:'教育制度を改革する必要がある。',         exTrans:'교육 제도를 개혁할 필요가 있다.'},
  {id:23, kanji:'方法',    reading:'ほうほう',     type:'noun', meaning:'방법',               example:'もっといい方法があります。',            exTrans:'더 좋은 방법이 있습니다.'},
  {id:24, kanji:'費用',    reading:'ひよう',       type:'noun', meaning:'비용',               example:'旅行の費用はいくらですか。',            exTrans:'여행 비용은 얼마입니까?'},
  {id:25, kanji:'内容',    reading:'ないよう',     type:'noun', meaning:'내용',               example:'メールの内容を確認しました。',           exTrans:'이메일 내용을 확인했습니다.'},
  {id:26, kanji:'現実',    reading:'げんじつ',     type:'noun', meaning:'현실',               example:'現実を受け入れなければならない。',       exTrans:'현실을 받아들여야 한다.'},
  {id:27, kanji:'印象',    reading:'いんしょう',   type:'noun', meaning:'인상',               example:'初めての印象はとても大切です。',         exTrans:'첫인상은 매우 중요합니다.'},
  {id:28, kanji:'記録',    reading:'きろく',       type:'noun', meaning:'기록',               example:'世界記録を破った。',                    exTrans:'세계 기록을 깼다.'},
  {id:29, kanji:'意識',    reading:'いしき',       type:'noun', meaning:'의식, 자각',          example:'環境への意識が高まっています。',         exTrans:'환경에 대한 의식이 높아지고 있습니다.'},
  {id:30, kanji:'努力',    reading:'どりょく',     type:'noun', meaning:'노력',               example:'努力すれば夢は叶う。',                  exTrans:'노력하면 꿈은 이루어진다.'},
  {id:31, kanji:'成功',    reading:'せいこう',     type:'noun', meaning:'성공',               example:'成功の秘訣は継続です。',                exTrans:'성공의 비결은 지속입니다.'},
  {id:32, kanji:'失敗',    reading:'しっぱい',     type:'noun', meaning:'실패',               example:'失敗から学ぶことが大切だ。',            exTrans:'실패에서 배우는 것이 중요하다.'},
  {id:33, kanji:'変化',    reading:'へんか',       type:'noun', meaning:'변화',               example:'季節の変化を楽しんでいます。',           exTrans:'계절의 변화를 즐기고 있습니다.'},
  {id:34, kanji:'増加',    reading:'ぞうか',       type:'noun', meaning:'증가',               example:'人口の増加が問題になっています。',       exTrans:'인구 증가가 문제가 되고 있습니다.'},
  {id:35, kanji:'減少',    reading:'げんしょう',   type:'noun', meaning:'감소',               example:'売り上げが減少している。',              exTrans:'매출이 감소하고 있다.'},
  {id:36, kanji:'報告',    reading:'ほうこく',     type:'noun', meaning:'보고',               example:'調査の報告をまとめました。',            exTrans:'조사 보고서를 정리했습니다.'},
  {id:37, kanji:'議論',    reading:'ぎろん',       type:'noun', meaning:'의론, 토론',          example:'この問題についてもっと議論が必要だ。',   exTrans:'이 문제에 대해 더 많은 논의가 필요하다.'},
  {id:38, kanji:'判断',    reading:'はんだん',     type:'noun', meaning:'판단',               example:'自分で判断してください。',              exTrans:'스스로 판단하세요.'},
  {id:39, kanji:'機会',    reading:'きかい',       type:'noun', meaning:'기회',               example:'いい機会ですから、挑戦してみましょう。', exTrans:'좋은 기회이니 도전해 봅시다.'},
  {id:40, kanji:'条件',    reading:'じょうけん',   type:'noun', meaning:'조건',               example:'給与の条件を確認してください。',         exTrans:'급여 조건을 확인해 주세요.'},
  {id:41, kanji:'生産',    reading:'せいさん',     type:'noun', meaning:'생산',               example:'この工場は車を生産しています。',         exTrans:'이 공장은 차를 생산합니다.'},
  {id:42, kanji:'消費',    reading:'しょうひ',     type:'noun', meaning:'소비',               example:'エネルギーの消費を減らしましょう。',     exTrans:'에너지 소비를 줄입시다.'},
  {id:43, kanji:'割合',    reading:'わりあい',     type:'noun', meaning:'비율',               example:'女性の割合が増えています。',            exTrans:'여성의 비율이 늘고 있습니다.'},
  {id:44, kanji:'手続き',  reading:'てつづき',     type:'noun', meaning:'절차, 수속',          example:'申請の手続きを教えてください。',         exTrans:'신청 절차를 알려 주세요.'},
  {id:45, kanji:'担当',    reading:'たんとう',     type:'noun', meaning:'담당',               example:'担当者に連絡してください。',            exTrans:'담당자에게 연락해 주세요.'},
  {id:46, kanji:'資料',    reading:'しりょう',     type:'noun', meaning:'자료, 문서',          example:'参考資料をお送りします。',              exTrans:'참고 자료를 보내드리겠습니다.'},
  {id:47, kanji:'申し込み',reading:'もうしこみ',   type:'noun', meaning:'신청',               example:'申し込みの締め切りは来週です。',         exTrans:'신청 마감은 다음 주입니다.'},
  {id:48, kanji:'進歩',    reading:'しんぽ',       type:'noun', meaning:'진보, 발전',          example:'科学の進歩は速い。',                    exTrans:'과학의 진보는 빠르다.'},
  {id:49, kanji:'発展',    reading:'はってん',     type:'noun', meaning:'발전, 성장',          example:'この地域の発展は著しい。',              exTrans:'이 지역의 발전은 현저하다.'},
  {id:50, kanji:'必要性',  reading:'ひつようせい', type:'noun', meaning:'필요성',              example:'変化の必要性を感じる。',                exTrans:'변화의 필요성을 느낀다.'},
  // ── VERBS ──
  {id:51, kanji:'確認する',reading:'かくにんする',  type:'verb', meaning:'확인하다',            example:'予約を確認してください。',              exTrans:'예약을 확인해 주세요.'},
  {id:52, kanji:'利用する',reading:'りようする',    type:'verb', meaning:'이용하다',            example:'公共交通を利用しています。',            exTrans:'대중교통을 이용하고 있습니다.'},
  {id:53, kanji:'参加する',reading:'さんかする',    type:'verb', meaning:'참가하다',            example:'会議に参加しました。',                  exTrans:'회의에 참가했습니다.'},
  {id:54, kanji:'提案する',reading:'ていあんする',  type:'verb', meaning:'제안하다',            example:'新しいアイデアを提案しました。',         exTrans:'새로운 아이디어를 제안했습니다.'},
  {id:55, kanji:'調査する',reading:'ちょうさする',  type:'verb', meaning:'조사하다',            example:'市場を調査しています。',                exTrans:'시장을 조사하고 있습니다.'},
  {id:56, kanji:'感動する',reading:'かんどうする',  type:'verb', meaning:'감동하다',            example:'その映画に感動しました。',              exTrans:'그 영화에 감동받았습니다.'},
  {id:57, kanji:'満足する',reading:'まんぞくする',  type:'verb', meaning:'만족하다',            example:'仕事に満足しています。',                exTrans:'일에 만족하고 있습니다.'},
  {id:58, kanji:'期待する',reading:'きたいする',    type:'verb', meaning:'기대하다',            example:'いい結果を期待しています。',            exTrans:'좋은 결과를 기대하고 있습니다.'},
  {id:59, kanji:'説明する',reading:'せつめいする',  type:'verb', meaning:'설명하다',            example:'もう一度説明してください。',            exTrans:'다시 한 번 설명해 주세요.'},
  {id:60, kanji:'受け入れる',reading:'うけいれる',  type:'verb', meaning:'받아들이다',           example:'変化を受け入れることが大切だ。',         exTrans:'변화를 받아들이는 것이 중요하다.'},
  {id:61, kanji:'気づく',  reading:'きづく',       type:'verb', meaning:'알아차리다',           example:'間違いに気づきました。',                exTrans:'실수를 알아차렸습니다.'},
  {id:62, kanji:'乗り越える',reading:'のりこえる',  type:'verb', meaning:'극복하다',            example:'困難を乗り越えました。',                exTrans:'어려움을 극복했습니다.'},
  {id:63, kanji:'繰り返す',reading:'くりかえす',    type:'verb', meaning:'반복하다',            example:'同じ間違いを繰り返さないでください。',   exTrans:'같은 실수를 반복하지 마세요.'},
  {id:64, kanji:'求める',  reading:'もとめる',     type:'verb', meaning:'구하다, 요구하다',     example:'解決策を求めています。',                exTrans:'해결책을 구하고 있습니다.'},
  {id:65, kanji:'認める',  reading:'みとめる',     type:'verb', meaning:'인정하다',            example:'間違いを認めることが大切だ。',           exTrans:'실수를 인정하는 것이 중요하다.'},
  {id:66, kanji:'断る',    reading:'ことわる',     type:'verb', meaning:'거절하다',            example:'丁寧に断りました。',                    exTrans:'정중하게 거절했습니다.'},
  {id:67, kanji:'悩む',    reading:'なやむ',       type:'verb', meaning:'고민하다',            example:'将来について悩んでいます。',            exTrans:'미래에 대해 고민하고 있습니다.'},
  {id:68, kanji:'諦める',  reading:'あきらめる',   type:'verb', meaning:'포기하다',            example:'夢を諦めないでください。',              exTrans:'꿈을 포기하지 마세요.'},
  {id:69, kanji:'挑戦する',reading:'ちょうせんする',type:'verb', meaning:'도전하다',            example:'新しいことに挑戦するのが好きです。',     exTrans:'새로운 것에 도전하는 것을 좋아합니다.'},
  {id:70, kanji:'示す',    reading:'しめす',       type:'verb', meaning:'나타내다, 보이다',     example:'データが問題を示しています。',           exTrans:'데이터가 문제를 나타내고 있습니다.'},
  {id:71, kanji:'述べる',  reading:'のべる',       type:'verb', meaning:'진술하다, 말하다',     example:'意見を述べてください。',                exTrans:'의견을 말씀해 주세요.'},
  {id:72, kanji:'従う',    reading:'したがう',     type:'verb', meaning:'따르다',              example:'ルールに従ってください。',              exTrans:'규칙을 따라 주세요.'},
  {id:73, kanji:'比較する',reading:'ひかくする',    type:'verb', meaning:'비교하다',            example:'二つの方法を比較してみましょう。',       exTrans:'두 가지 방법을 비교해 봅시다.'},
  {id:74, kanji:'支持する',reading:'しじする',     type:'verb', meaning:'지지하다',            example:'この政策を支持しています。',            exTrans:'이 정책을 지지합니다.'},
  {id:75, kanji:'実現する',reading:'じつげんする',  type:'verb', meaning:'실현하다',            example:'夢を実現するために頑張っています。',     exTrans:'꿈을 실현하기 위해 열심히 하고 있습니다.'},
  {id:76, kanji:'取り組む',reading:'とりくむ',     type:'verb', meaning:'씨름하다, 몰두하다',    example:'新しいプロジェクトに取り組んでいます。', exTrans:'새 프로젝트에 임하고 있습니다.'},
  {id:77, kanji:'話し合う',reading:'はなしあう',    type:'verb', meaning:'서로 이야기하다',      example:'問題について話し合いましょう。',         exTrans:'문제에 대해 이야기해 봅시다.'},
  {id:78, kanji:'整える',  reading:'ととのえる',   type:'verb', meaning:'정비하다, 갖추다',     example:'環境を整えることが大切だ。',            exTrans:'환경을 갖추는 것이 중요하다.'},
  {id:79, kanji:'見直す',  reading:'みなおす',     type:'verb', meaning:'재검토하다',           example:'計画を見直す必要がある。',              exTrans:'계획을 재검토할 필요가 있다.'},
  {id:80, kanji:'引き起こす',reading:'ひきおこす',  type:'verb', meaning:'일으키다, 야기하다',    example:'ストレスが病気を引き起こす。',           exTrans:'스트레스가 병을 야기한다.'},
  // ── ADJECTIVES ──
  {id:81, kanji:'複雑な',  reading:'ふくざつな',   type:'adj',  meaning:'복잡한',              example:'この問題は複雑だ。',                    exTrans:'이 문제는 복잡하다.'},
  {id:82, kanji:'様々な',  reading:'さまざまな',   type:'adj',  meaning:'다양한',              example:'様々な意見がある。',                    exTrans:'다양한 의견이 있다.'},
  {id:83, kanji:'適切な',  reading:'てきせつな',   type:'adj',  meaning:'적절한',              example:'適切な対応が必要だ。',                  exTrans:'적절한 대응이 필요하다.'},
  {id:84, kanji:'重要な',  reading:'じゅうような',  type:'adj',  meaning:'중요한',              example:'重要な情報があります。',                exTrans:'중요한 정보가 있습니다.'},
  {id:85, kanji:'正確な',  reading:'せいかくな',   type:'adj',  meaning:'정확한',              example:'正確な情報を提供してください。',         exTrans:'정확한 정보를 제공해 주세요.'},
  {id:86, kanji:'積極的な',reading:'せっきょくてきな',type:'adj',meaning:'적극적인',             example:'積極的に参加してください。',            exTrans:'적극적으로 참여해 주세요.'},
  {id:87, kanji:'具体的な',reading:'ぐたいてきな',  type:'adj',  meaning:'구체적인',             example:'具体的な例を挙げてください。',           exTrans:'구체적인 예를 들어 주세요.'},
  {id:88, kanji:'一般的な',reading:'いっぱんてきな', type:'adj', meaning:'일반적인',             example:'一般的な考え方です。',                  exTrans:'일반적인 사고방식입니다.'},
  {id:89, kanji:'効果的な',reading:'こうかてきな',  type:'adj',  meaning:'효과적인',             example:'効果的な方法を探しています。',           exTrans:'효과적인 방법을 찾고 있습니다.'},
  {id:90, kanji:'現実的な',reading:'げんじつてきな', type:'adj', meaning:'현실적인',             example:'現実的な計画を立てましょう。',           exTrans:'현실적인 계획을 세웁시다.'},
  {id:91, kanji:'深刻な',  reading:'しんこくな',   type:'adj',  meaning:'심각한',              example:'深刻な問題です。',                      exTrans:'심각한 문제입니다.'},
  {id:92, kanji:'豊かな',  reading:'ゆたかな',     type:'adj',  meaning:'풍요로운',             example:'豊かな自然があります。',                exTrans:'풍요로운 자연이 있습니다.'},
  {id:93, kanji:'素直な',  reading:'すなおな',     type:'adj',  meaning:'솔직한, 순수한',       example:'素直な子どもです。',                    exTrans:'솔직한 아이입니다.'},
  {id:94, kanji:'冷静な',  reading:'れいせいな',   type:'adj',  meaning:'냉정한',              example:'冷静に判断してください。',              exTrans:'냉정하게 판단해 주세요.'},
  {id:95, kanji:'正直な',  reading:'しょうじきな', type:'adj',  meaning:'정직한',              example:'正直に答えてください。',                exTrans:'정직하게 대답해 주세요.'},
  {id:96, kanji:'謙虚な',  reading:'けんきょな',   type:'adj',  meaning:'겸손한',              example:'謙虚な態度が大切です。',                exTrans:'겸손한 태도가 중요합니다.'},
  {id:97, kanji:'柔軟な',  reading:'じゅうなんな', type:'adj',  meaning:'유연한',              example:'柔軟な対応が必要です。',                exTrans:'유연한 대응이 필요합니다.'},
  {id:98, kanji:'急激な',  reading:'きゅうげきな', type:'adj',  meaning:'급격한',              example:'急激な変化がありました。',              exTrans:'급격한 변화가 있었습니다.'},
  {id:99, kanji:'合理的な',reading:'ごうりてきな', type:'adj',  meaning:'합리적인',             example:'合理的な判断です。',                    exTrans:'합리적인 판단입니다.'},
  {id:100,kanji:'多様な',  reading:'たような',     type:'adj',  meaning:'다양한',              example:'多様な価値観があります。',              exTrans:'다양한 가치관이 있습니다.'},
  // ── ADVERBS ──
  {id:101,kanji:'特に',    reading:'とくに',       type:'adv',  meaning:'특히, 특별히',         example:'特に問題はありません。',                exTrans:'특별히 문제는 없습니다.'},
  {id:102,kanji:'さらに',  reading:'さらに',       type:'adv',  meaning:'더욱, 게다가',         example:'さらに努力が必要です。',                exTrans:'더욱 노력이 필요합니다.'},
  {id:103,kanji:'むしろ',  reading:'むしろ',       type:'adv',  meaning:'오히려',              example:'むしろ逆効果だった。',                  exTrans:'오히려 역효과였다.'},
  {id:104,kanji:'少なくとも',reading:'すくなくとも',type:'adv', meaning:'적어도',              example:'少なくとも1時間かかります。',           exTrans:'적어도 1시간 걸립니다.'},
  {id:105,kanji:'ほとんど',reading:'ほとんど',     type:'adv',  meaning:'거의',               example:'ほとんど終わりました。',                exTrans:'거의 끝났습니다.'},
  {id:106,kanji:'わずか',  reading:'わずか',       type:'adv',  meaning:'겨우, 불과',          example:'わずか5分で終わりました。',              exTrans:'불과 5분에 끝났습니다.'},
  {id:107,kanji:'次第に',  reading:'しだいに',     type:'adv',  meaning:'점차, 차츰',          example:'次第に慣れてきました。',                exTrans:'점차 익숙해졌습니다.'},
  {id:108,kanji:'急に',    reading:'きゅうに',     type:'adv',  meaning:'갑자기',              example:'急に雨が降り始めた。',                  exTrans:'갑자기 비가 내리기 시작했다.'},
  {id:109,kanji:'確かに',  reading:'たしかに',     type:'adv',  meaning:'확실히',              example:'確かにその通りです。',                  exTrans:'확실히 그렇습니다.'},
  {id:110,kanji:'直接',    reading:'ちょくせつ',   type:'adv',  meaning:'직접',               example:'直接会って話しましょう。',              exTrans:'직접 만나서 이야기합시다.'},
  {id:111,kanji:'できるだけ',reading:'できるだけ',  type:'adv',  meaning:'가능한 한',            example:'できるだけ早く連絡します。',            exTrans:'가능한 한 빨리 연락하겠습니다.'},
  {id:112,kanji:'しっかり',reading:'しっかり',     type:'adv',  meaning:'단단히, 제대로',       example:'しっかり準備してください。',            exTrans:'제대로 준비해 주세요.'},
  {id:113,kanji:'あらかじめ',reading:'あらかじめ', type:'adv',  meaning:'미리, 사전에',         example:'あらかじめ確認してください。',           exTrans:'미리 확인해 주세요.'},
  {id:114,kanji:'互いに',  reading:'たがいに',     type:'adv',  meaning:'서로',               example:'互いに助け合いましょう。',              exTrans:'서로 도웁시다.'},
  {id:115,kanji:'一方',    reading:'いっぽう',     type:'adv',  meaning:'한편',               example:'一方、問題もあります。',                exTrans:'한편, 문제도 있습니다.'},
  {id:116,kanji:'それぞれ',reading:'それぞれ',     type:'adv',  meaning:'각각',               example:'それぞれ違う意見があります。',           exTrans:'각각 다른 의견이 있습니다.'},
  {id:117,kanji:'主に',    reading:'おもに',       type:'adv',  meaning:'주로',               example:'主に若者が利用しています。',            exTrans:'주로 젊은이들이 이용하고 있습니다.'},
  {id:118,kanji:'実際に',  reading:'じっさいに',   type:'adv',  meaning:'실제로',              example:'実際に試してみましょう。',              exTrans:'실제로 해봅시다.'},
  {id:119,kanji:'意外に',  reading:'いがいに',     type:'adv',  meaning:'의외로',              example:'意外に簡単でした。',                    exTrans:'의외로 쉬웠습니다.'},
  {id:120,kanji:'正式に',  reading:'せいしきに',   type:'adv',  meaning:'정식으로',             example:'正式に発表されました。',                exTrans:'정식으로 발표되었습니다.'},
];
