const VOCAB_N3 = [
  // ── DAY-1 ──
  {id:1,   kanji:'書類',     reading:'しょるい',   type:'noun', meaning:'서류',         example:'書類を提出してください。',         exTrans:'서류를 제출해 주세요.'},
  {id:2,   kanji:'書店',     reading:'しょてん',   type:'noun', meaning:'서점',         example:'書店で本を買いました。',           exTrans:'서점에서 책을 샀습니다.'},
  {id:3,   kanji:'資料',     reading:'しりょう',   type:'noun', meaning:'자료',         example:'資料を準備します。',               exTrans:'자료를 준비합니다.'},
  {id:4,   kanji:'資金',     reading:'しきん',     type:'noun', meaning:'자금',         example:'資金が足りません。',               exTrans:'자금이 부족합니다.'},
  {id:5,   kanji:'資格',     reading:'しかく',     type:'noun', meaning:'자격',         example:'資格を取りたいです。',             exTrans:'자격증을 취득하고 싶습니다.'},
  {id:6,   kanji:'信号',     reading:'しんごう',   type:'noun', meaning:'신호',         example:'信号を守ってください。',           exTrans:'신호를 지켜 주세요.'},
  {id:7,   kanji:'信用',     reading:'しんよう',   type:'noun', meaning:'신용',         example:'信用が大切です。',                 exTrans:'신용이 중요합니다.'},
  {id:8,   kanji:'身長',     reading:'しんちょう', type:'noun', meaning:'신장/키',       example:'身長を測りました。',               exTrans:'키를 쟀습니다.'},
  {id:9,   kanji:'進歩',     reading:'しんぽ',     type:'noun', meaning:'진보',         example:'科学が進歩しました。',             exTrans:'과학이 진보했습니다.'},
  {id:10,  kanji:'進行',     reading:'しんこう',   type:'noun', meaning:'진행',         example:'工事が進行中です。',               exTrans:'공사가 진행 중입니다.'},
  {id:11,  kanji:'深夜',     reading:'しんや',     type:'noun', meaning:'심야',         example:'深夜に帰りました。',               exTrans:'심야에 돌아왔습니다.'},
  {id:12,  kanji:'深刻',     reading:'しんこく',   type:'noun', meaning:'심각',         example:'深刻な問題です。',                 exTrans:'심각한 문제입니다.'},
  {id:13,  kanji:'水泳',     reading:'すいえい',   type:'noun', meaning:'수영',         example:'水泳が得意です。',                 exTrans:'수영을 잘합니다.'},
  {id:14,  kanji:'水道',     reading:'すいどう',   type:'noun', meaning:'수도',         example:'水道水を使います。',               exTrans:'수돗물을 사용합니다.'},
  {id:15,  kanji:'数学',     reading:'すうがく',   type:'noun', meaning:'수학',         example:'数学が好きです。',                 exTrans:'수학을 좋아합니다.'},
  {id:16,  kanji:'数字',     reading:'すうじ',     type:'noun', meaning:'숫자',         example:'数字を確認します。',               exTrans:'숫자를 확인합니다.'},
  {id:17,  kanji:'成功',     reading:'せいこう',   type:'noun', meaning:'성공',         example:'成功おめでとうございます。',       exTrans:'성공을 축하합니다.'},
  {id:18,  kanji:'成長',     reading:'せいちょう', type:'noun', meaning:'성장',         example:'子供が成長しました。',             exTrans:'아이가 성장했습니다.'},
  {id:19,  kanji:'成人',     reading:'せいじん',   type:'noun', meaning:'성인',         example:'成人式がありました。',             exTrans:'성인식이 있었습니다.'},
  {id:20,  kanji:'大人',     reading:'おとな',     type:'noun', meaning:'어른',         example:'大人の対応が必要です。',           exTrans:'어른다운 대응이 필요합니다.'},
  {id:21,  kanji:'制服',     reading:'せいふく',   type:'noun', meaning:'교복/제복',    example:'学校の制服を着ます。',             exTrans:'학교 교복을 입습니다.'},
  {id:22,  kanji:'税金',     reading:'ぜいきん',   type:'noun', meaning:'세금',         example:'税金を払います。',                 exTrans:'세금을 납부합니다.'},
  {id:23,  kanji:'免税',     reading:'めんぜい',   type:'noun', meaning:'면세',         example:'免税品を買いました。',             exTrans:'면세품을 샀습니다.'},
  {id:24,  kanji:'免税店',   reading:'めんぜいてん',type:'noun',meaning:'면세점',        example:'空港の免税店に寄りました。',       exTrans:'공항 면세점에 들렀습니다.'},
  {id:25,  kanji:'生徒',     reading:'せいと',     type:'noun', meaning:'학생',         example:'生徒が勉強しています。',           exTrans:'학생이 공부하고 있습니다.'},
  {id:26,  kanji:'生物',     reading:'せいぶつ',   type:'noun', meaning:'생물',         example:'生物の授業です。',                 exTrans:'생물 수업입니다.'},
  {id:27,  kanji:'生産',     reading:'せいさん',   type:'noun', meaning:'생산',         example:'生産量が増えました。',             exTrans:'생산량이 늘었습니다.'},
  {id:28,  kanji:'西洋',     reading:'せいよう',   type:'noun', meaning:'서양',         example:'西洋の文化を学びます。',           exTrans:'서양 문화를 배웁니다.'},
  {id:29,  kanji:'東洋',     reading:'とうよう',   type:'noun', meaning:'동양',         example:'東洋医学に興味があります。',       exTrans:'동양 의학에 흥미가 있습니다.'},
  {id:30,  kanji:'世界',     reading:'せかい',     type:'noun', meaning:'세계',         example:'世界中を旅したいです。',           exTrans:'전 세계를 여행하고 싶습니다.'},
  {id:31,  kanji:'世間',     reading:'せけん',     type:'noun', meaning:'세간/세상',    example:'世間の目が気になります。',         exTrans:'세상의 시선이 신경 쓰입니다.'},
  {id:32,  kanji:'世話',     reading:'せわ',       type:'noun', meaning:'신세/돌봄',    example:'お世話になりました。',             exTrans:'신세를 졌습니다.'},
  {id:33,  kanji:'世の中',   reading:'よのなか',   type:'noun', meaning:'세상',         example:'世の中が変わりました。',           exTrans:'세상이 변했습니다.'},
  {id:34,  kanji:'席',       reading:'せき',       type:'noun', meaning:'자리',         example:'席に座ってください。',             exTrans:'자리에 앉아 주세요.'},
  {id:35,  kanji:'満席',     reading:'まんせき',   type:'noun', meaning:'만석',         example:'飛行機は満席です。',               exTrans:'비행기는 만석입니다.'},
  {id:36,  kanji:'空席',     reading:'くうせき',   type:'noun', meaning:'빈자리',       example:'空席はありますか。',               exTrans:'빈자리가 있습니까?'},
  {id:37,  kanji:'説明',     reading:'せつめい',   type:'noun', meaning:'설명',         example:'もう一度説明してください。',       exTrans:'다시 한 번 설명해 주세요.'},
  {id:38,  kanji:'選手',     reading:'せんしゅ',   type:'noun', meaning:'선수',         example:'選手として活躍します。',           exTrans:'선수로서 활약합니다.'},
  {id:39,  kanji:'選択',     reading:'せんたく',   type:'noun', meaning:'선택',         example:'自由に選択できます。',             exTrans:'자유롭게 선택할 수 있습니다.'},
  {id:40,  kanji:'洗濯',     reading:'せんたく',   type:'noun', meaning:'세탁',         example:'洗濯物を干します。',               exTrans:'빨래를 널어 말립니다.'},
  {id:41,  kanji:'専門',     reading:'せんもん',   type:'noun', meaning:'전문',         example:'専門家に相談します。',             exTrans:'전문가에게 상담합니다.'},
  {id:42,  kanji:'専攻',     reading:'せんこう',   type:'noun', meaning:'전공',         example:'大学の専攻は何ですか。',           exTrans:'대학 전공이 무엇입니까?'},
  {id:43,  kanji:'想像',     reading:'そうぞう',   type:'noun', meaning:'상상',         example:'想像以上でした。',                 exTrans:'상상 이상이었습니다.'},
  {id:44,  kanji:'相談',     reading:'そうだん',   type:'noun', meaning:'상담',         example:'先生に相談しました。',             exTrans:'선생님께 상담했습니다.'},
  {id:45,  kanji:'早朝',     reading:'そうちょう', type:'noun', meaning:'이른 아침',    example:'早朝に出発します。',               exTrans:'이른 아침에 출발합니다.'},
  {id:46,  kanji:'送別',     reading:'そうべつ',   type:'noun', meaning:'송별',         example:'送別パーティーをします。',         exTrans:'송별 파티를 합니다.'},
  {id:47,  kanji:'送別会',   reading:'そうべつかい',type:'noun',meaning:'송별회',        example:'送別会を開きました。',             exTrans:'송별회를 열었습니다.'},
  {id:48,  kanji:'歓迎',     reading:'かんげい',   type:'noun', meaning:'환영',         example:'心から歓迎します。',               exTrans:'마음으로 환영합니다.'},
  {id:49,  kanji:'歓迎会',   reading:'かんげいかい',type:'noun',meaning:'환영회',        example:'歓迎会を開きました。',             exTrans:'환영회를 열었습니다.'},
  {id:50,  kanji:'速度',     reading:'そくど',     type:'noun', meaning:'속도',         example:'速度を落としてください。',         exTrans:'속도를 줄여 주세요.'},
  {id:51,  kanji:'卒業',     reading:'そつぎょう', type:'noun', meaning:'졸업',         example:'大学を卒業しました。',             exTrans:'대학을 졸업했습니다.'},
  {id:52,  kanji:'入学',     reading:'にゅうがく', type:'noun', meaning:'입학',         example:'来年入学します。',                 exTrans:'내년에 입학합니다.'},
  {id:53,  kanji:'祖父',     reading:'そふ',       type:'noun', meaning:'할아버지',     example:'祖父は元気です。',                 exTrans:'할아버지는 건강합니다.'},
  {id:54,  kanji:'祖母',     reading:'そぼ',       type:'noun', meaning:'할머니',       example:'祖母に会いに行きます。',           exTrans:'할머니를 만나러 갑니다.'},
  {id:55,  kanji:'父',       reading:'ちち',       type:'noun', meaning:'아버지',       example:'父は会社員です。',                 exTrans:'아버지는 회사원입니다.'},
  {id:56,  kanji:'母',       reading:'はは',       type:'noun', meaning:'어머니',       example:'母は料理が上手です。',             exTrans:'어머니는 요리를 잘합니다.'},
  // ── DAY-2 ──
  {id:57,  kanji:'体格',     reading:'たいかく',   type:'noun', meaning:'체격',         example:'体格がいいですね。',               exTrans:'체격이 좋네요.'},
  {id:58,  kanji:'体操',     reading:'たいそう',   type:'noun', meaning:'체조',         example:'毎朝体操をします。',               exTrans:'매일 아침 체조를 합니다.'},
  {id:59,  kanji:'体力',     reading:'たいりょく', type:'noun', meaning:'체력',         example:'体力をつけましょう。',             exTrans:'체력을 기릅시다.'},
  {id:60,  kanji:'体重',     reading:'たいじゅう', type:'noun', meaning:'체중',         example:'体重が増えました。',               exTrans:'체중이 늘었습니다.'},
  {id:61,  kanji:'体',       reading:'からだ',     type:'noun', meaning:'몸',           example:'体を大切にしてください。',         exTrans:'몸을 소중히 해 주세요.'},
  {id:62,  kanji:'退院',     reading:'たいいん',   type:'noun', meaning:'퇴원',         example:'明日退院します。',                 exTrans:'내일 퇴원합니다.'},
  {id:63,  kanji:'代表',     reading:'だいひょう', type:'noun', meaning:'대표',         example:'代表として発表します。',           exTrans:'대표로서 발표합니다.'},
  {id:64,  kanji:'代理',     reading:'だいり',     type:'noun', meaning:'대리',         example:'代理で出席しました。',             exTrans:'대리로 출석했습니다.'},
  {id:65,  kanji:'単語',     reading:'たんご',     type:'noun', meaning:'단어',         example:'単語を覚えます。',                 exTrans:'단어를 외웁니다.'},
  {id:66,  kanji:'短所',     reading:'たんしょ',   type:'noun', meaning:'단점',         example:'自分の短所を知っています。',       exTrans:'자신의 단점을 알고 있습니다.'},
  {id:67,  kanji:'長所',     reading:'ちょうしょ', type:'noun', meaning:'장점',         example:'長所を活かしましょう。',           exTrans:'장점을 살립시다.'},
  {id:68,  kanji:'団体',     reading:'だんたい',   type:'noun', meaning:'단체',         example:'団体旅行に参加します。',           exTrans:'단체 여행에 참가합니다.'},
  {id:69,  kanji:'担当',     reading:'たんとう',   type:'noun', meaning:'담당',         example:'担当者に連絡します。',             exTrans:'담당자에게 연락합니다.'},
  {id:70,  kanji:'暖房',     reading:'だんぼう',   type:'noun', meaning:'난방',         example:'暖房をつけました。',               exTrans:'난방을 켰습니다.'},
  {id:71,  kanji:'地球',     reading:'ちきゅう',   type:'noun', meaning:'지구',         example:'地球を守りましょう。',             exTrans:'지구를 지킵시다.'},
  {id:72,  kanji:'地区',     reading:'ちく',       type:'noun', meaning:'지구/구역',    example:'この地区に住んでいます。',         exTrans:'이 구역에 살고 있습니다.'},
  {id:73,  kanji:'地域',     reading:'ちいき',     type:'noun', meaning:'지역',         example:'地域の人と協力します。',           exTrans:'지역 주민과 협력합니다.'},
  {id:74,  kanji:'地図',     reading:'ちず',       type:'noun', meaning:'지도',         example:'地図を見て探しました。',           exTrans:'지도를 보고 찾았습니다.'},
  {id:75,  kanji:'地下鉄',   reading:'ちかてつ',   type:'noun', meaning:'지하철',       example:'地下鉄で通勤します。',             exTrans:'지하철로 통근합니다.'},
  {id:76,  kanji:'地震',     reading:'じしん',     type:'noun', meaning:'지진',         example:'地震に備えましょう。',             exTrans:'지진에 대비합시다.'},
  {id:77,  kanji:'遅刻',     reading:'ちこく',     type:'noun', meaning:'지각',         example:'遅刻してすみません。',             exTrans:'지각해서 죄송합니다.'},
  {id:78,  kanji:'知識',     reading:'ちしき',     type:'noun', meaning:'지식',         example:'知識を身につけます。',             exTrans:'지식을 쌓습니다.'},
  {id:79,  kanji:'知能',     reading:'ちのう',     type:'noun', meaning:'지능',         example:'知能が高いです。',                 exTrans:'지능이 높습니다.'},
  {id:80,  kanji:'知人',     reading:'ちじん',     type:'noun', meaning:'지인',         example:'知人に会いました。',               exTrans:'지인을 만났습니다.'},
  {id:81,  kanji:'注意',     reading:'ちゅうい',   type:'noun', meaning:'주의',         example:'注意してください。',               exTrans:'주의해 주세요.'},
  {id:82,  kanji:'注目',     reading:'ちゅうもく', type:'noun', meaning:'주목',         example:'注目を集めています。',             exTrans:'주목을 받고 있습니다.'},
  {id:83,  kanji:'中央',     reading:'ちゅうおう', type:'noun', meaning:'중앙',         example:'中央に座ります。',                 exTrans:'중앙에 앉습니다.'},
  {id:84,  kanji:'中古',     reading:'ちゅうこ',   type:'noun', meaning:'중고',         example:'中古の車を買いました。',           exTrans:'중고차를 샀습니다.'},
  {id:85,  kanji:'中止',     reading:'ちゅうし',   type:'noun', meaning:'중지',         example:'試合が中止になりました。',         exTrans:'시합이 중지되었습니다.'},
  {id:86,  kanji:'中国',     reading:'ちゅうごく', type:'noun', meaning:'중국',         example:'中国語を勉強します。',             exTrans:'중국어를 공부합니다.'},
  {id:87,  kanji:'調査',     reading:'ちょうさ',   type:'noun', meaning:'조사',         example:'調査結果が出ました。',             exTrans:'조사 결과가 나왔습니다.'},
  {id:88,  kanji:'朝食',     reading:'ちょうしょく',type:'noun',meaning:'아침 식사',    example:'朝食を食べました。',               exTrans:'아침 식사를 먹었습니다.'},
  {id:89,  kanji:'貯金',     reading:'ちょきん',   type:'noun', meaning:'저금',         example:'貯金が増えました。',               exTrans:'저금이 늘었습니다.'},
  {id:90,  kanji:'追加',     reading:'ついか',     type:'noun', meaning:'추가',         example:'追加注文をします。',               exTrans:'추가 주문을 합니다.'},
  {id:91,  kanji:'通過',     reading:'つうか',     type:'noun', meaning:'통과',         example:'電車が通過しました。',             exTrans:'전철이 통과했습니다.'},
  {id:92,  kanji:'通勤',     reading:'つうきん',   type:'noun', meaning:'통근',         example:'電車で通勤します。',               exTrans:'전철로 통근합니다.'},
  {id:93,  kanji:'通学',     reading:'つうがく',   type:'noun', meaning:'통학',         example:'バスで通学します。',               exTrans:'버스로 통학합니다.'},
  {id:94,  kanji:'通行',     reading:'つうこう',   type:'noun', meaning:'통행',         example:'通行禁止です。',                   exTrans:'통행 금지입니다.'},
  {id:95,  kanji:'通知',     reading:'つうち',     type:'noun', meaning:'통지',         example:'通知が届きました。',               exTrans:'통지가 도착했습니다.'},
  {id:96,  kanji:'通訳',     reading:'つうやく',   type:'noun', meaning:'통역',         example:'通訳が必要ですか。',               exTrans:'통역이 필요합니까?'},
  {id:97,  kanji:'通路',     reading:'つうろ',     type:'noun', meaning:'통로',         example:'通路を歩いてください。',           exTrans:'통로로 걸어 주세요.'},
  {id:98,  kanji:'交通',     reading:'こうつう',   type:'noun', meaning:'교통',         example:'交通事故に気をつけます。',         exTrans:'교통사고에 주의합니다.'},
  {id:99,  kanji:'停止',     reading:'ていし',     type:'noun', meaning:'정지',         example:'車が停止しました。',               exTrans:'차가 정지했습니다.'},
  {id:100, kanji:'停電',     reading:'ていでん',   type:'noun', meaning:'정전',         example:'停電になりました。',               exTrans:'정전이 되었습니다.'},
];
